package model;

import java.util.List;

import com.google.common.collect.Lists;

/**
 * This class extends ItemSet model object and adds features to a itemset specific to AprioriTID
 * implementation. This includes extensions and generators.
 * 
 * @author shishir
 *
 */
public class AprioriTidItemSet extends ItemSet 
{
	// List of itemsets in previous pass which generated this itemset
	private int[] generators;
	
	// List of itemsets which were generated by extendin this itemset
	private List<Integer> extensions;
	
	public AprioriTidItemSet(List<Integer> items, int supportCount)
	{
		super(items, supportCount);
		
		this.generators = new int[2];
		this.extensions = Lists.newArrayList();
	}
	
	public AprioriTidItemSet(List<Integer> items, int supportCount, Integer gen1, Integer gen2)
	{
		this(items, supportCount);
		
		generators[0] = gen1;
		generators[1] = gen2;
	}

	public int[] getGenerators() {
		return generators;
	}

	public List<Integer> getExtensions() {
		return extensions;
	}
	
	public void addExtension(Integer extension)
	{
		this.extensions.add(extension);
	}

}
